# -*- coding: utf-8 -*-
"""
/***************************************************************************
 m150xml
                                 A QGIS plugin
 Import Lines and Points (Manholes and sewers) from  DWA XML 150
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-12-18
        copyright            : (C) 2019 by gerd 3er geoplaning GmbH
        email                : kontakt@geoplaning.de

        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load m150xml class from file m150xml.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .m150xml import m150xml
    return m150xml(iface)
